//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication6
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infragistics.Samples.Shared.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Build-in Theme:.
        /// </summary>
        public static string ChooseBuildinTheme {
            get {
                return ResourceManager.GetString("ChooseBuildinTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color Scheme:.
        /// </summary>
        public static string ChooseColorScheme {
            get {
                return ResourceManager.GetString("ChooseColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string ConfigurationPanel_Header_Options {
            get {
                return ResourceManager.GetString("ConfigurationPanel_Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Color:.
        /// </summary>
        public static string SelectAColor {
            get {
                return ResourceManager.GetString("SelectAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme:.
        /// </summary>
        public static string ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Time.
        /// </summary>
        public static string XW_BindingTime {
            get {
                return ResourceManager.GetString("XW_BindingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string XW_Clear_Window_Button_Label {
            get {
                return ResourceManager.GetString("XW_Clear_Window_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Points.
        /// </summary>
        public static string XW_DataPoints {
            get {
                return ResourceManager.GetString("XW_DataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string XW_Date {
            get {
                return ResourceManager.GetString("XW_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Alignment.
        /// </summary>
        public static string XW_HorizontalAlignment {
            get {
                return ResourceManager.GetString("XW_HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string XW_Opacity {
            get {
                return ResourceManager.GetString("XW_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIONS.
        /// </summary>
        public static string XW_Options {
            get {
                return ResourceManager.GetString("XW_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pane Visibility.
        /// </summary>
        public static string XW_PaneVisibility {
            get {
                return ResourceManager.GetString("XW_PaneVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        public static string XW_Property_Brush {
            get {
                return ResourceManager.GetString("XW_Property_Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string XW_Property_Thickness {
            get {
                return ResourceManager.GetString("XW_Property_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        public static string XW_SampleStatus_Initialized {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        public static string XW_SampleStatus_Initializing {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string XW_SampleStatus_Loaded {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded items..
        /// </summary>
        public static string XW_SampleStatus_LoadedItems {
            get {
                return ResourceManager.GetString("XW_SampleStatus_LoadedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string XW_SampleStatus_Loading {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading item.
        /// </summary>
        public static string XW_SampleStatus_LoadingItem {
            get {
                return ResourceManager.GetString("XW_SampleStatus_LoadingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (CTP).
        /// </summary>
        public static string XW_SampleTag_CTP {
            get {
                return ResourceManager.GetString("XW_SampleTag_CTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NEW).
        /// </summary>
        public static string XW_SampleTag_NEW {
            get {
                return ResourceManager.GetString("XW_SampleTag_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string XW_Settings {
            get {
                return ResourceManager.GetString("XW_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: CIA World Factbook.
        /// </summary>
        public static string XW_Source_CIA {
            get {
                return ResourceManager.GetString("XW_Source_CIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: GeoCommons Service.
        /// </summary>
        public static string XW_Source_GeoCommons {
            get {
                return ResourceManager.GetString("XW_Source_GeoCommons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: Microsoft BingMaps, OpenStreetMap, and CloudMadeMaps.
        /// </summary>
        public static string XW_Source_GeoImagery {
            get {
                return ResourceManager.GetString("XW_Source_GeoImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: MapQuest, OpenStreetMap, NASA/JPL-Caltech, and U.S. DOA.
        /// </summary>
        public static string XW_Source_MapQuest {
            get {
                return ResourceManager.GetString("XW_Source_MapQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: NOAA National Weather Service.
        /// </summary>
        public static string XW_Source_NOAA {
            get {
                return ResourceManager.GetString("XW_Source_NOAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: U.S. Census Bureau.
        /// </summary>
        public static string XW_Source_USCB {
            get {
                return ResourceManager.GetString("XW_Source_USCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: U.S. Geological Survey.
        /// </summary>
        public static string XW_Source_USGS {
            get {
                return ResourceManager.GetString("XW_Source_USGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: National Atlas of the United States.
        /// </summary>
        public static string XW_Source_USNA {
            get {
                return ResourceManager.GetString("XW_Source_USNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE: National Atlas of the United States and CIA World Factbook.
        /// </summary>
        public static string XW_Source_USNA_CIA {
            get {
                return ResourceManager.GetString("XW_Source_USNA_CIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Theme:.
        /// </summary>
        public static string XW_ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Theme.
        /// </summary>
        public static string XW_ThemeSupport_DefaultTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IG Theme.
        /// </summary>
        public static string XW_ThemeSupport_IGTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_IGTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro Theme.
        /// </summary>
        public static string XW_ThemeSupport_Metro {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 2010 Blue Theme.
        /// </summary>
        public static string XW_ThemeSupport_Office2010BlueTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Office2010BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string XW_ThemeSupport_Themes {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string XW_Time {
            get {
                return ResourceManager.GetString("XW_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Span.
        /// </summary>
        public static string XW_TimeSpan {
            get {
                return ResourceManager.GetString("XW_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string XW_Value {
            get {
                return ResourceManager.GetString("XW_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment.
        /// </summary>
        public static string XW_VerticalAlignment {
            get {
                return ResourceManager.GetString("XW_VerticalAlignment", resourceCulture);
            }
        }
    }
}
