//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornPeatsTeXingDongTaiChart {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public CommonStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CornPeatsTeXingDongTaiChart.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Build-in Theme: 的本地化字符串。
        /// </summary>
        public static string ChooseBuildinTheme {
            get {
                return ResourceManager.GetString("ChooseBuildinTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Color Scheme: 的本地化字符串。
        /// </summary>
        public static string ChooseColorScheme {
            get {
                return ResourceManager.GetString("ChooseColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string ConfigurationPanel_Header_Options {
            get {
                return ResourceManager.GetString("ConfigurationPanel_Header_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷蠹和米象对小麦的虫蚀粒和千粒重影响 的本地化字符串。
        /// </summary>
        public static string Maintitle {
            get {
                return ResourceManager.GetString("Maintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Color: 的本地化字符串。
        /// </summary>
        public static string SelectAColor {
            get {
                return ResourceManager.GetString("SelectAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Theme: 的本地化字符串。
        /// </summary>
        public static string ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding Time 的本地化字符串。
        /// </summary>
        public static string XW_BindingTime {
            get {
                return ResourceManager.GetString("XW_BindingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string XW_Clear_Window_Button_Label {
            get {
                return ResourceManager.GetString("XW_Clear_Window_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Points 的本地化字符串。
        /// </summary>
        public static string XW_DataPoints {
            get {
                return ResourceManager.GetString("XW_DataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string XW_Date {
            get {
                return ResourceManager.GetString("XW_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转变函数 的本地化字符串。
        /// </summary>
        public static string XW_Funtions {
            get {
                return ResourceManager.GetString("XW_Funtions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Alignment 的本地化字符串。
        /// </summary>
        public static string XW_HorizontalAlignment {
            get {
                return ResourceManager.GetString("XW_HorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转变持续时间 的本地化字符串。
        /// </summary>
        public static string XW_IntertTime {
            get {
                return ResourceManager.GetString("XW_IntertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择头数 的本地化字符串。
        /// </summary>
        public static string XW_Main_ComBobox {
            get {
                return ResourceManager.GetString("XW_Main_ComBobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动态折线图 的本地化字符串。
        /// </summary>
        public static string XW_Main_Lab1 {
            get {
                return ResourceManager.GetString("XW_Main_Lab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折线图 的本地化字符串。
        /// </summary>
        public static string XW_Main_Lab2 {
            get {
                return ResourceManager.GetString("XW_Main_Lab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条形图 的本地化字符串。
        /// </summary>
        public static string XW_Main_Lab3 {
            get {
                return ResourceManager.GetString("XW_Main_Lab3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opacity 的本地化字符串。
        /// </summary>
        public static string XW_Opacity {
            get {
                return ResourceManager.GetString("XW_Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OPTIONS 的本地化字符串。
        /// </summary>
        public static string XW_Options {
            get {
                return ResourceManager.GetString("XW_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pane Visibility 的本地化字符串。
        /// </summary>
        public static string XW_PaneVisibility {
            get {
                return ResourceManager.GetString("XW_PaneVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brush 的本地化字符串。
        /// </summary>
        public static string XW_Property_Brush {
            get {
                return ResourceManager.GetString("XW_Property_Brush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thickness 的本地化字符串。
        /// </summary>
        public static string XW_Property_Thickness {
            get {
                return ResourceManager.GetString("XW_Property_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 动画执行时间 的本地化字符串。
        /// </summary>
        public static string XW_RunTime {
            get {
                return ResourceManager.GetString("XW_RunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialized 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_Initialized {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_Initializing {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_Loaded {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaded items. 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_LoadedItems {
            get {
                return ResourceManager.GetString("XW_SampleStatus_LoadedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_Loading {
            get {
                return ResourceManager.GetString("XW_SampleStatus_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading item 的本地化字符串。
        /// </summary>
        public static string XW_SampleStatus_LoadingItem {
            get {
                return ResourceManager.GetString("XW_SampleStatus_LoadingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (CTP) 的本地化字符串。
        /// </summary>
        public static string XW_SampleTag_CTP {
            get {
                return ResourceManager.GetString("XW_SampleTag_CTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (NEW) 的本地化字符串。
        /// </summary>
        public static string XW_SampleTag_NEW {
            get {
                return ResourceManager.GetString("XW_SampleTag_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string XW_Settings {
            get {
                return ResourceManager.GetString("XW_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: CIA World Factbook 的本地化字符串。
        /// </summary>
        public static string XW_Source_CIA {
            get {
                return ResourceManager.GetString("XW_Source_CIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: GeoCommons Service 的本地化字符串。
        /// </summary>
        public static string XW_Source_GeoCommons {
            get {
                return ResourceManager.GetString("XW_Source_GeoCommons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: Microsoft BingMaps, OpenStreetMap, and CloudMadeMaps 的本地化字符串。
        /// </summary>
        public static string XW_Source_GeoImagery {
            get {
                return ResourceManager.GetString("XW_Source_GeoImagery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: MapQuest, OpenStreetMap, NASA/JPL-Caltech, and U.S. DOA 的本地化字符串。
        /// </summary>
        public static string XW_Source_MapQuest {
            get {
                return ResourceManager.GetString("XW_Source_MapQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: NOAA National Weather Service 的本地化字符串。
        /// </summary>
        public static string XW_Source_NOAA {
            get {
                return ResourceManager.GetString("XW_Source_NOAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: U.S. Census Bureau 的本地化字符串。
        /// </summary>
        public static string XW_Source_USCB {
            get {
                return ResourceManager.GetString("XW_Source_USCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: U.S. Geological Survey 的本地化字符串。
        /// </summary>
        public static string XW_Source_USGS {
            get {
                return ResourceManager.GetString("XW_Source_USGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: National Atlas of the United States 的本地化字符串。
        /// </summary>
        public static string XW_Source_USNA {
            get {
                return ResourceManager.GetString("XW_Source_USNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SOURCE: National Atlas of the United States and CIA World Factbook 的本地化字符串。
        /// </summary>
        public static string XW_Source_USNA_CIA {
            get {
                return ResourceManager.GetString("XW_Source_USNA_CIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Theme: 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_ComboLabel {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_ComboLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Theme 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_DefaultTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_DefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IG Theme 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_IGTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_IGTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metro Theme 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_Metro {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Metro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Office 2010 Blue Theme 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_Office2010BlueTheme {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Office2010BlueTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Themes 的本地化字符串。
        /// </summary>
        public static string XW_ThemeSupport_Themes {
            get {
                return ResourceManager.GetString("XW_ThemeSupport_Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string XW_Time {
            get {
                return ResourceManager.GetString("XW_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Span 的本地化字符串。
        /// </summary>
        public static string XW_TimeSpan {
            get {
                return ResourceManager.GetString("XW_TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小麦的虫蚀粒和千粒重变化图 的本地化字符串。
        /// </summary>
        public static string XW_Title {
            get {
                return ResourceManager.GetString("XW_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string XW_Value {
            get {
                return ResourceManager.GetString("XW_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Alignment 的本地化字符串。
        /// </summary>
        public static string XW_VerticalAlignment {
            get {
                return ResourceManager.GetString("XW_VerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似       湿度: 的本地化字符串。
        /// </summary>
        public static string XW_Win1_Hum {
            get {
                return ResourceManager.GetString("XW_Win1_Hum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  最高温度: 的本地化字符串。
        /// </summary>
        public static string XW_Win1_MaxTem {
            get {
                return ResourceManager.GetString("XW_Win1_MaxTem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  最低温度: 的本地化字符串。
        /// </summary>
        public static string XW_Win1_MinTem {
            get {
                return ResourceManager.GetString("XW_Win1_MinTem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;X:&quot; 的本地化字符串。
        /// </summary>
        public static string XWDC_ChartScrollIntoView_XAxisScrollIntoView {
            get {
                return ResourceManager.GetString("XWDC_ChartScrollIntoView_XAxisScrollIntoView", resourceCulture);
            }
        }
    }
}
